apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: "{{{TRAVIS_COMMIT}}}"
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{{TRAVIS_COMMIT}}}"
  name: watch-keeper
  labels:
    razee/watch-resource: "lite"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: watch-keeper
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: watch-keeper
        razee/watch-resource: "lite"
      name: watch-keeper
    spec:
      serviceAccountName: watch-keeper-sa
      securityContext:
        runAsUser: {{{NODE_USER_ID}}}
        runAsGroup: {{{NODE_GROUP_ID}}}
        fsGroup: {{{NODE_GROUP_ID}}}
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_EXTRA_CA_CERTS
              value: /home/node/envs/watch-keeper-secret/cacerts.pem
            - name: USER_AGENT_NAME
              value: razee-io/watchkeeper
            - name: USER_AGENT_VERSION
              value: "{{{TRAVIS_TAG}}}"
            - name: NODE_ENV
              value: "production"
            - name: KUBECONFIG
              valueFrom:
                configMapKeyRef:
                  name: watch-keeper-config
                  key: KUBECONFIG
                  optional: true
          image: "quay.io/razee/watch-keeper:{{{TRAVIS_TAG}}}"
          imagePullPolicy: Always
          name: watch-keeper
          resources:
            limits:
              memory: 500Mi
              cpu: 400m
            requests:
              memory: 100Mi
              cpu: 50m
          livenessProbe:
            exec:
              command:
                - sh/liveness.sh
            initialDelaySeconds: 600
            periodSeconds: 300
            timeoutSeconds: 30
            failureThreshold: 1
            successThreshold: 1
          volumeMounts:
            - name: watch-keeper-config
              mountPath: /home/node/envs/watch-keeper-config
            - name: watch-keeper-secret
              mountPath: /home/node/envs/watch-keeper-secret
            - name: razee-identity-config
              mountPath: /home/node/envs/razee-identity-config
            - name: razee-identity-secret
              mountPath: /home/node/envs/razee-identity-secret
      volumes:
        - name: watch-keeper-config
          configMap:
            name: watch-keeper-config
            defaultMode: 0400
            optional: true
        - name: watch-keeper-secret
          secret:
            secretName: watch-keeper-secret
            defaultMode: 0400
            optional: true
        - name: razee-identity-config
          configMap:
            name: razee-identity
            defaultMode: 0400
            optional: true
        - name: razee-identity-secret
          secret:
            secretName: razee-identity
            defaultMode: 0400
            optional: true
